package org.example;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AsientosSala {
    private JButton a1;
    private JLabel AsientosLabel;
    public JPanel MaiinPanel;
    private JButton a2;
    private JButton a3;
    private JButton a4;
    private JButton a5;
    private JButton a6;
    private JButton a7;
    private JButton a8;
    private JButton a9;
    private JButton a10;
    private JButton a11;
    private JButton a12;
    private JButton a13;
    private JButton a14;
    private JButton a15;
    private JButton a29;
    private JButton a43;
    private JButton a57;
    private JButton a71;
    private JButton a85;
    private JButton a99;
    private JButton a113;
    private JButton a127;
    private JButton a141;
    private JButton a155;
    private JButton a16;
    private JButton a17;
    private JButton a18;
    private JButton a19;
    private JButton a20;
    private JButton a21;
    private JButton a22;
    private JButton a23;
    private JButton a24;
    private JButton a25;
    private JButton a26;
    private JButton a27;
    private JButton a28;
    private JButton a42;
    private JButton a56;
    private JButton a55;
    private JButton a41;
    private JButton a40;
    private JButton a39;
    private JButton a38;
    private JButton a37;
    private JButton a36;
    private JButton a35;
    private JButton a34;
    private JButton a33;
    private JButton a32;
    private JButton a31;
    private JButton a30;
    private JButton a44;
    private JButton a58;
    private JButton a72;
    private JButton a86;
    private JButton a100;
    private JButton a114;
    private JButton a128;
    private JButton a142;
    private JButton a156;
    private JButton a157;
    private JButton a158;
    private JButton a159;
    private JButton a160;
    private JButton a161;
    private JButton a162;
    private JButton a163;
    private JButton a164;
    private JButton a165;
    private JButton a166;
    private JButton a167;
    private JButton a168;
    private JButton a154;
    private JButton a140;
    private JButton a126;
    private JButton a112;
    private JButton a98;
    private JButton a84;
    private JButton a70;
    private JButton a69;
    private JButton a83;
    private JButton a97;
    private JButton a111;
    private JButton a125;
    private JButton a139;
    private JButton a153;
    private JButton a152;
    private JButton a138;
    private JButton a124;
    private JButton a110;
    private JButton a96;
    private JButton a82;
    private JButton a68;
    private JButton a54;
    private JButton a53;
    private JButton a52;
    private JButton a51;
    private JButton a50;
    private JButton a49;
    private JButton a48;
    private JButton a47;
    private JButton a46;
    private JButton a45;
    private JButton a59;
    private JButton a73;
    private JButton a87;
    private JButton a101;
    private JButton a115;
    private JButton a129;
    private JButton a143;
    private JButton a144;
    private JButton a130;
    private JButton a131;
    private JButton a145;
    private JButton a146;
    private JButton a132;
    private JButton a133;
    private JButton a147;
    private JButton a134;
    private JButton a148;
    private JButton a135;
    private JButton a136;
    private JButton a137;
    private JButton a149;
    private JButton a150;
    private JButton a151;
    private JButton a123;
    private JButton a109;
    private JButton a95;
    private JButton a81;
    private JButton a67;
    private JButton a66;
    private JButton a65;
    private JButton a64;
    private JButton a63;
    private JButton a62;
    private JButton a61;
    private JButton a60;
    private JButton a74;
    private JButton a75;
    private JButton a88;
    private JButton a102;
    private JButton a116;
    private JButton a117;
    private JButton a103;
    private JButton a89;
    private JButton a76;
    private JButton a90;
    private JButton a104;
    private JButton a118;
    private JButton a119;
    private JButton a105;
    private JButton a91;
    private JButton a77;
    private JButton a78;
    private JButton a92;
    private JButton a106;
    private JButton a120;
    private JButton a121;
    private JButton a107;
    private JButton a93;
    private JButton a79;
    private JButton a80;
    private JButton a94;
    private JButton a108;
    private JButton a122;
    private JButton a170;
    private JButton a171;
    private JButton a172;
    private JButton a173;
    private JButton a174;
    private JButton a175;
    private JButton a176;
    private JButton a177;
    private JButton a178;
    private JButton a179;
    private JButton a180;
    private JButton a181;
    private JButton a182;
    private JButton a183;
    private JButton a184;
    private JButton a169;
    private JButton a185;
    private JButton a186;
    private JButton a187;
    private JButton a188;
    private JButton a189;
    private JButton a190;
    private JButton a191;
    private JButton a192;
    private JButton a193;
    private JButton a194;
    private JButton a195;
    private JButton a196;
    private JButton a197;
    private JButton a198;
    private JButton a199;
    private JButton a200;
    private JButton regresarButton;
    private JButton reelegirAsientosButton;
    private JButton reservarButton;

    public AsientosSala() {
        PELICULAS nueva = new PELICULAS();
        ReservaPelicula reservacion = new ReservaPelicula();
        String peli = "", fecha1="", salaVer="", horaVer="";
        reservacion.guardar(peli,fecha1,salaVer,horaVer);
        System.out.println(peli);
        System.out.println(fecha1);
        System.out.println(salaVer);
        System.out.println(horaVer);
        regresarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame reservar = new JFrame();
                reservar.setTitle("PoliCine");
                reservar.setContentPane(new ReservaPelicula().MainPanel);
                reservar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                reservar.setSize(500, 350);
                reservar.setLocationRelativeTo(null);
                reservar.setVisible(true);
                ImageIcon imagen = new ImageIcon("IMAGENES/POLICINE_ICON.png");
                reservar.setIconImage(imagen.getImage());
                ((JFrame) SwingUtilities.getWindowAncestor(regresarButton)).dispose();
            }
        });
    }
}
